gains:
#  suspension_left_joint:  {p: 30000,  d: 250, i: 0.1, i_clamp: 1.5}
#  suspension_right_joint: {p: 30000,  d: 250, i: 0.1, i_clamp: 1.5}
  head_1_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
  head_2_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
#  xtion_frame_joint: {p: 0.5,  d: 0, i: 0, i_clamp: 1.5}

  FFJ4: &shadow_gains {p: 100,  d: 0,  i: 10}
  FFJ3: *shadow_gains
  FFJ2: *shadow_gains
  FFJ1: *shadow_gains
  MFJ4: *shadow_gains
  MFJ3: *shadow_gains
  MFJ2: *shadow_gains
  MFJ1: *shadow_gains
  RFJ4: *shadow_gains
  RFJ3: *shadow_gains
  RFJ2: *shadow_gains
  RFJ1: *shadow_gains
  THJ5: *shadow_gains
  THJ4: *shadow_gains
  THJ2: *shadow_gains
  THJ1: *shadow_gains

velocity:
  pid_gains:
     wheel_right_joint: {p: 30,  d: 0, i: 0, i_clamp: 1.0}
     wheel_left_joint:  {p: 30,  d: 0, i: 0, i_clamp: 1.0}
#     caster_front_right_1_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
#     caster_front_right_2_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
#     caster_front_left_1_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
#     caster_front_left_2_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
#     caster_back_right_1_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
#     caster_back_right_2_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
#     caster_back_left_1_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
#     caster_back_left_2_joint: {p: 0,  d: 0,  i: 0, i_clamp: 0}
